import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/shared/layout/nav-bar";
import { fetchAllCategories } from "@ecommerce-front/features/catalog/services/type-product/get";
import { SearchProvider } from "@/shared/search/search-context";
import { CartProvider } from "@/shared/cart/cart-context";
import CartAside from "@/shared/cart/cart-aside";
import { Toaster } from "react-hot-toast";
import { AdminAuthProvider } from "@/shared/auth/admin-auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch categories on the server and pass to NavBar (avoid client fetching)
  let categories: Array<{ documentId?: string; type: string }> = [];
  try {
    const res = await fetchAllCategories();
    categories = Array.isArray(res?.data) ? res.data : [];
  } catch {}
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AdminAuthProvider>
          <CartProvider>
            <SearchProvider>
              <NavBar categories={categories} />
              <CartAside />
              <main className="mt-16 sm:mt-[72px] lg:mt-20">
                {children}
              </main>
            </SearchProvider>
            <Toaster
              position="bottom-right"
              toastOptions={{
                duration: 2000,
                style: {
                  padding: '16px 24px',
                  fontSize: '1rem',
                  background: '#1e77af',
                  color: '#fff',
                  borderRadius: '12px',
                },
                success: {
                  iconTheme: {
                    primary: '#10b981',
                    secondary: '#d1fae5',
                  },
                },
              }}
            />
          </CartProvider>
        </AdminAuthProvider>
      </body>
    </html>
  );
}
